CREATE OR REPLACE PROCEDURE BACKUP_INFO(BACKUP_TIME TIMESTAMP) AS
    CURSOR ct1 IS
    SELECT *
    FROM LOGS
    WHERE TIME >= BACKUP_TIME
    ORDER BY TIME;
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER STUDENTS_LOGS_TRIGGER DISABLE';
    FOR record IN ct1
    LOOP
        IF record.ACTION = 'INSERT' THEN
            DELETE FROM STUDENTS WHERE ID = record.STUDENT_ID;
        ELSIF record.ACTION = 'UPDATE' THEN
            UPDATE STUDENTS
            SET NAME = record.OLD_STUDENT_NAME, GROUP_ID = record.OLD_STUDENT_GROUP_ID
            WHERE ID = record.STUDENT_ID;
        ELSE
            INSERT INTO STUDENTS(ID, NAME, GROUP_ID)
            VALUES (record.STUDENT_ID, record.OLD_STUDENT_NAME, record.OLD_STUDENT_GROUP_ID);
        END IF;
    END LOOP;
    EXECUTE IMMEDIATE 'ALTER TRIGGER STUDENTS_LOGS_TRIGGER ENABLE';
END;
/