CREATE OR REPLACE TRIGGER GROUPS_C_VAL_UPDATE_TRIGGER
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE GROUPS 
        SET C_VAL = C_VAL + 1 
        WHERE ID = :NEW.GROUP_ID;
    ELSIF UPDATING THEN
        UPDATE GROUPS 
        SET C_VAL = C_VAL + 1 
        WHERE ID = :NEW.GROUP_ID;

        UPDATE GROUPS 
        SET C_VAL = C_VAL - 1 
        WHERE ID = :OLD.GROUP_ID;
    ELSIF DELETING THEN
        UPDATE GROUPS 
        SET C_VAL = C_VAL - 1 
        WHERE ID = :OLD.GROUP_ID;
    END IF;
END;
/