DECLARE
    
BEGIN
    SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'USERNAME' AND TABLE_NAME = 'MYTABLE'
    ORDER BY COLUMN_NAME;

    SELECT ALL_CONS_COLUMNS.COLUMN_NAME, ALL_CONS_COLUMNS.CONSTRAINT_NAME, 
            ALL_CONSTRAINTS.CONSTRAINT_TYPE
    FROM ALL_CONS_COLUMNS
    JOIN ALL_CONSTRAINTS
    ON ALL_CONSTRAINTS.TABLE_NAME = ALL_CONS_COLUMNS.TABLE_NAME
    WHERE ALL_CONSTRAINTS.OWNER = 'USERNAME' 
        AND REGEXP_LIKE (ALL_CONS_COLUMNS.CONSTRAINT_NAME, 'SYS%|BIN%')
        AND ALL_CONS_COLUMNS.TABLE_NAME = 'MYTABLE'
    ORDER BY ALL_CONS_COLUMNS.CONSTRAINT_NAME;
END;